let listData = {
  result: 0,
  companys: [
    {
      id: 1616,
      nm: "KARAM",
      pId: 1610,
    },
    {
      id: 1652,
      nm: "GDDP",
      pId: 1610,
    },
    {
      id: 1679,
      nm: "aimotive",
      pId: 1610,
    },
    {
      id: 1802,
      nm: "ambeyenterprises",
      pId: 1610,
    },
    {
      id: 1812,
      nm: "bababrickfield",
      pId: 1610,
    },
    {
      id: 1931,
      nm: "AmbeyAdmin",
      pId: 1802,
    },
    {
      id: 1956,
      nm: "play",
      pId: 1610,
    },
    {
      id: 2055,
      nm: "Akmal",
      pId: 1610,
    },
    {
      id: 2294,
      nm: "dashcam",
      pId: 1610,
    },
    {
      id: 1610,
      nm: "Motive Surveillance",
      pId: 1462,
    },
  ],
  vehicles: [
    {
      id: 47696,
      nm: "UP32QN0491",
      ic: 2,
      pid: 1616,
      pnm: "KARAM",
      abbr: "",
      dl: [
        {
          id: "018270237117",
          pid: 1616,
          dt: null,
          cc: 4,
          cn: "CH1,CH2,CH3,CH4",
          ic: 0,
          io: "",
          outc: null,
          outn: null,
          tc: 0,
          tn: "",
          sim: null,
          md: 361,
          st: null,
          nflt: null,
          us: 0,
          sdc: null,
          did: 51430,
          vt: null,
          isb: null,
          srl: "",
          ptt: null,
          gps: null,
          fp: null,
          tkc: null,
          ist: "2024-11-17 03:04:07",
          ol: null,
          lt: null,
        },
      ],
      pt: "黄牌",
      vehiColor: null,
      status: 0,
      vehiBand: "",
      vehiType: null,
      vehiUse: "",
      dateProduct: -19800000,
      icon: 2,
      chnCount: 4,
      chnName: "CH1,CH2,CH3,CH4",
      ioInCount: 0,
      ioInName: "",
      ioOutCount: 0,
      ioOutName: "",
      tempCount: 0,
      tempName: "",
      payEnable: null,
      payBegin: 1731781800000,
      payEnd: null,
      payMonth: null,
      payDelayDay: 0,
      safeDate: null,
      drivingNum: "",
      drivingDate: -28800000,
      operatingNum: "",
      operatingDate: -28800000,
      repairDate: null,
      stlTm: 1731781800000,
      moreId: null,
      vehicleGrade: "",
      approvedNumber: null,
      approvedLoad: null,
      vehicleType: 0,
      installTire: 0,
      tireBrand: "",
      tireModel: "",
      installAdas: 0,
      adasBrand: "",
      adasModel: "",
      installDsm: 0,
      dsmBrand: "",
      dsmModel: "",
      installBlind: 0,
      blindBrand: "",
      blindModel: "",
      installLca: 0,
      lcaBrand: "",
      lcaModel: "",
      installOM: 0,
      engineNum: "",
      frameNum: "",
      ownerName: null,
      lineId: null,
      linkPeople: "",
      linkPhone: "",
      datePurchase: -19800000,
      dateAnnualSurvey: -19800000,
      speedLimit: 0,
      linesOperation: "",
      operatingId: null,
      industry: null,
      carType: null,
      carPlace: null,
      param1: "",
      param2: "",
      param3: "",
      param4: "",
      roleId: null,
      area: "",
      code: "",
      nuclearAuthority: "",
      legal: "",
      legalPhone: "",
      legalAddress: "",
      introduction: "",
      serialNum: null,
      loginPwd: null,
      allowLogin: 0,
      mileCoefficient: null,
      remark: "",
      vehicleModel: "",
      engineModel: "",
      axesNumber: null,
      totalWeight: null,
      quasiTractionMass: null,
      longOutlineDimensions: null,
      wideOutlineDimensions: null,
      highOutlineDimensions: null,
      longInsideDimension: null,
      wideInnerDimensions: null,
      highInsideDimensions: null,
      ombrand: "",
      ommodel: "",
    },
    {
      id: 47697,
      nm: "UP32LN0244",
      ic: 2,
      pid: 1616,
      pnm: "KARAM",
      abbr: "",
      dl: [
        {
          id: "018270236717",
          pid: 1616,
          dt: null,
          cc: 4,
          cn: "CH1,CH2,CH3,CH4",
          ic: 0,
          io: "",
          outc: null,
          outn: null,
          tc: 0,
          tn: "",
          sim: "8991542404593582878",
          md: 361,
          st: null,
          nflt: null,
          us: 0,
          sdc: null,
          did: 51431,
          vt: null,
          isb: null,
          srl: "",
          ptt: null,
          gps: null,
          fp: null,
          tkc: null,
          ist: "2024-11-17 03:17:13",
          ol: null,
          lt: null,
        },
      ],
      pt: "黄牌",
      vehiColor: null,
      status: 0,
      vehiBand: "",
      vehiType: null,
      vehiUse: "",
      dateProduct: -19800000,
      icon: 2,
      chnCount: 4,
      chnName: "CH1,CH2,CH3,CH4",
      ioInCount: 0,
      ioInName: "",
      ioOutCount: 0,
      ioOutName: "",
      tempCount: 0,
      tempName: "",
      payEnable: null,
      payBegin: 1731781800000,
      payEnd: null,
      payMonth: null,
      payDelayDay: 0,
      safeDate: null,
      drivingNum: "",
      drivingDate: -115200000,
      operatingNum: "",
      operatingDate: -115200000,
      repairDate: null,
      stlTm: 1731781800000,
      moreId: null,
      vehicleGrade: "",
      approvedNumber: null,
      approvedLoad: null,
      vehicleType: 0,
      installTire: 0,
      tireBrand: "",
      tireModel: "",
      installAdas: 0,
      adasBrand: "",
      adasModel: "",
      installDsm: 0,
      dsmBrand: "",
      dsmModel: "",
      installBlind: 0,
      blindBrand: "",
      blindModel: "",
      installLca: 0,
      lcaBrand: "",
      lcaModel: "",
      installOM: 0,
      engineNum: "",
      frameNum: "",
      ownerName: null,
      lineId: null,
      linkPeople: "",
      linkPhone: "",
      datePurchase: -19800000,
      dateAnnualSurvey: -19800000,
      speedLimit: 0,
      linesOperation: "",
      operatingId: null,
      industry: null,
      carType: null,
      carPlace: null,
      param1: "",
      param2: "",
      param3: "",
      param4: "",
      roleId: null,
      area: "",
      code: "",
      nuclearAuthority: "",
      legal: "",
      legalPhone: "",
      legalAddress: "",
      introduction: "",
      serialNum: null,
      loginPwd: null,
      allowLogin: 0,
      mileCoefficient: null,
      remark: "",
      vehicleModel: "",
      engineModel: "",
      axesNumber: null,
      totalWeight: null,
      quasiTractionMass: null,
      longOutlineDimensions: null,
      wideOutlineDimensions: null,
      highOutlineDimensions: null,
      longInsideDimension: null,
      wideInnerDimensions: null,
      highInsideDimensions: null,
      ombrand: "",
      ommodel: "",
    },
    {
      id: 47877,
      nm: "UP41AT8502",
      ic: 2,
      pid: 1802,
      pnm: "ambeyenterprises",
      abbr: "",
      dl: [
        {
          id: "018270714649",
          pid: 1802,
          dt: null,
          cc: 4,
          cn: "CH1,CH2,CH3,CH4",
          ic: 0,
          io: "",
          outc: null,
          outn: null,
          tc: 0,
          tn: "",
          sim: null,
          md: 361,
          st: null,
          nflt: null,
          us: 0,
          sdc: null,
          did: 51625,
          vt: null,
          isb: null,
          srl: "",
          ptt: null,
          gps: null,
          fp: null,
          tkc: null,
          ist: "2024-12-19 01:01:01",
          ol: null,
          lt: null,
        },
      ],
      pt: "黄牌",
      vehiColor: null,
      status: 0,
      vehiBand: "",
      vehiType: null,
      vehiUse: "",
      dateProduct: -19800000,
      icon: 2,
      chnCount: 4,
      chnName: "CH1,CH2,CH3,CH4",
      ioInCount: 0,
      ioInName: "",
      ioOutCount: 0,
      ioOutName: "",
      tempCount: 0,
      tempName: "",
      payEnable: null,
      payBegin: 1734460200000,
      payEnd: null,
      payMonth: null,
      payDelayDay: 0,
      safeDate: null,
      drivingNum: "",
      drivingDate: -28800000,
      operatingNum: "",
      operatingDate: -28800000,
      repairDate: null,
      stlTm: 1734460200000,
      moreId: null,
      vehicleGrade: "",
      approvedNumber: null,
      approvedLoad: null,
      vehicleType: 0,
      installTire: 0,
      tireBrand: "",
      tireModel: "",
      installAdas: 0,
      adasBrand: "",
      adasModel: "",
      installDsm: 0,
      dsmBrand: "",
      dsmModel: "",
      installBlind: 0,
      blindBrand: "",
      blindModel: "",
      installLca: 0,
      lcaBrand: "",
      lcaModel: "",
      installOM: 0,
      engineNum: "",
      frameNum: "",
      ownerName: null,
      lineId: null,
      linkPeople: "",
      linkPhone: "",
      datePurchase: -19800000,
      dateAnnualSurvey: -19800000,
      speedLimit: 0,
      linesOperation: "",
      operatingId: null,
      industry: null,
      carType: null,
      carPlace: null,
      param1: "",
      param2: "",
      param3: "",
      param4: "",
      roleId: null,
      area: "",
      code: "",
      nuclearAuthority: "",
      legal: "",
      legalPhone: "",
      legalAddress: "",
      introduction: "",
      serialNum: null,
      loginPwd: null,
      allowLogin: 0,
      mileCoefficient: null,
      remark: "",
      vehicleModel: "",
      engineModel: "",
      axesNumber: null,
      totalWeight: null,
      quasiTractionMass: null,
      longOutlineDimensions: null,
      wideOutlineDimensions: null,
      highOutlineDimensions: null,
      longInsideDimension: null,
      wideInnerDimensions: null,
      highInsideDimensions: null,
      ombrand: "",
      ommodel: "",
    },
    {
      id: 47695,
      nm: "UP32JN9504",
      ic: 2,
      pid: 1616,
      pnm: "KARAM",
      abbr: "",
      dl: [
        {
          id: "018270237096",
          pid: 1616,
          dt: null,
          cc: 4,
          cn: "CH1,CH2,CH3,CH4",
          ic: 0,
          io: "",
          outc: null,
          outn: null,
          tc: 0,
          tn: "",
          sim: null,
          md: 361,
          st: null,
          nflt: null,
          us: 0,
          sdc: null,
          did: 51429,
          vt: null,
          isb: null,
          srl: "",
          ptt: null,
          gps: null,
          fp: null,
          tkc: null,
          ist: "2024-11-17 02:37:20",
          ol: null,
          lt: null,
        },
      ],
      pt: "黄牌",
      vehiColor: null,
      status: 0,
      vehiBand: "",
      vehiType: null,
      vehiUse: "",
      dateProduct: -19800000,
      icon: 2,
      chnCount: 4,
      chnName: "CH1,CH2,CH3,CH4",
      ioInCount: 0,
      ioInName: "",
      ioOutCount: 0,
      ioOutName: "",
      tempCount: 0,
      tempName: "",
      payEnable: null,
      payBegin: 1731781800000,
      payEnd: null,
      payMonth: null,
      payDelayDay: 0,
      safeDate: null,
      drivingNum: "",
      drivingDate: -28800000,
      operatingNum: "",
      operatingDate: -28800000,
      repairDate: null,
      stlTm: 1731781800000,
      moreId: null,
      vehicleGrade: "",
      approvedNumber: null,
      approvedLoad: null,
      vehicleType: 0,
      installTire: 0,
      tireBrand: "",
      tireModel: "",
      installAdas: 0,
      adasBrand: "",
      adasModel: "",
      installDsm: 0,
      dsmBrand: "",
      dsmModel: "",
      installBlind: 0,
      blindBrand: "",
      blindModel: "",
      installLca: 0,
      lcaBrand: "",
      lcaModel: "",
      installOM: 0,
      engineNum: "",
      frameNum: "",
      ownerName: null,
      lineId: null,
      linkPeople: "",
      linkPhone: "",
      datePurchase: -19800000,
      dateAnnualSurvey: -19800000,
      speedLimit: 0,
      linesOperation: "",
      operatingId: null,
      industry: null,
      carType: null,
      carPlace: null,
      param1: "",
      param2: "",
      param3: "",
      param4: "",
      roleId: null,
      area: "",
      code: "",
      nuclearAuthority: "",
      legal: "",
      legalPhone: "",
      legalAddress: "",
      introduction: "",
      serialNum: null,
      loginPwd: null,
      allowLogin: 0,
      mileCoefficient: null,
      remark: "",
      vehicleModel: "",
      engineModel: "",
      axesNumber: null,
      totalWeight: null,
      quasiTractionMass: null,
      longOutlineDimensions: null,
      wideOutlineDimensions: null,
      highOutlineDimensions: null,
      longInsideDimension: null,
      wideInnerDimensions: null,
      highInsideDimensions: null,
      ombrand: "",
      ommodel: "",
    },
  ],
};

const newVehicleNmList = listData.vehicles.reduce((acc, vehicle) => {
  acc.push({ nm: vehicle.nm });
  return acc;
}, []); //[{nm:"iodiwe"},{nm:"isywiq7y"}]

let newVehicleDlIdList = listData.vehicles.map((vehicle) => {
  return vehicle.dl.reduce((acc, dl) => {
    acc = { id: dl.id };
    return acc;
  }, {});
});

// console.log(newVehicleNmList);
// console.log(newVehicleDlIdList);

let newVehicleList = newVehicleDlIdList.map((item, index) => {
  return { ...newVehicleDlIdList[index], ...newVehicleNmList[index] };
});

// console.log(newVehicleList);
